import dbConnect from '@/lib/db';
import Product from '@/models/Product';
import Bill from '@/models/Bill';
import { LayoutDashboard, Package, AlertTriangle, TrendingUp, FileText } from 'lucide-react';
import Link from 'next/link';

async function getStats() {
  await dbConnect();

  const productCount = await Product.countDocuments();
  const lowStockCount = await Product.countDocuments({ stock: { $lt: 5 } });
  const billCount = await Bill.countDocuments();

  // Calculate total revenue
  const revenueData = await Bill.aggregate([
    {
      $group: {
        _id: null,
        total: { $sum: "$totalAmount" }
      }
    }
  ]);
  const totalRevenue = revenueData.length > 0 ? revenueData[0].total : 0;

  // Get recent bills
  const recentBills = await Bill.find({})
    .sort({ createdAt: -1 })
    .limit(5)
    .populate('items.productId', 'name'); // Populate purely for display if reference exists

  return {
    productCount,
    lowStockCount,
    billCount,
    totalRevenue,
    recentBills: JSON.parse(JSON.stringify(recentBills)), // ID serialization
  };
}

export default async function Home() {
  const stats = await getStats();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">Dashboard</h1>
        <div className="flex space-x-2">
          <Link href="/billing" className="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 bg-zinc-900 text-zinc-50 hover:bg-zinc-900/90 h-10 px-4 py-2 dark:bg-zinc-50 dark:text-zinc-900 dark:hover:bg-zinc-50/90">
            Create New Bill
          </Link>
          <Link href="/products" className="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 border border-zinc-200 bg-white hover:bg-zinc-100 h-10 px-4 py-2 dark:border-zinc-800 dark:bg-zinc-950 dark:hover:bg-zinc-800 dark:text-zinc-50">
            Manage Products
          </Link>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card title="Total Products" value={stats.productCount} icon={Package} description="Active products in inventory" />
        <Card title="Low Stock Alerts" value={stats.lowStockCount} icon={AlertTriangle} description="Products with < 5 items" alert={stats.lowStockCount > 0} />
        <Card title="Total Bills" value={stats.billCount} icon={FileText} description="Total invoices generated" />
        <Card title="Total Revenue" value={`₹${stats.totalRevenue.toFixed(2)}`} icon={TrendingUp} description="Lifetime revenue" />
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-7">
        <div className="col-span-4 rounded-xl border border-zinc-200 bg-white text-zinc-950 shadow dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-50">
          <div className="flex flex-col space-y-1.5 p-6">
            <h3 className="font-semibold leading-none tracking-tight">Recent Transactions</h3>
            <p className="text-sm text-zinc-500 dark:text-zinc-400">Latest bills generated by the system.</p>
          </div>
          <div className="p-6 pt-0">
            <div className="relative w-full overflow-auto">
              <table className="w-full caption-bottom text-sm text-left">
                <thead className="[&_tr]:border-b">
                  <tr className="border-b transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800">
                    <th className="h-12 px-4 align-middle font-medium text-zinc-500 dark:text-zinc-400">Customer</th>
                    <th className="h-12 px-4 align-middle font-medium text-zinc-500 dark:text-zinc-400">Date</th>
                    <th className="h-12 px-4 align-middle font-medium text-zinc-500 dark:text-zinc-400 text-right">Amount</th>
                  </tr>
                </thead>
                <tbody className="[&_tr:last-child]:border-0">
                  {stats.recentBills.length === 0 ? (
                    <tr>
                      <td colSpan={3} className="p-4 text-center text-zinc-500">No recent bills found.</td>
                    </tr>
                  ) : (
                    stats.recentBills.map((bill) => (
                      <tr key={bill._id} className="border-b transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800">
                        <td className="p-4 align-middle font-medium">{bill.customerName}</td>
                        <td className="p-4 align-middle">{new Date(bill.createdAt).toLocaleDateString()}</td>
                        <td className="p-4 align-middle text-right">₹{bill.totalAmount.toFixed(2)}</td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function Card({ title, value, icon: Icon, description, alert }) {
  return (
    <div className={`rounded-xl border bg-white text-zinc-950 shadow dark:bg-zinc-950 dark:text-zinc-50 ${alert ? 'border-red-500' : 'border-zinc-200 dark:border-zinc-800'}`}>
      <div className="p-6 flex flex-row items-center justify-between space-y-0 pb-2">
        <h3 className="tracking-tight text-sm font-medium">{title}</h3>
        <Icon className={`h-4 w-4 ${alert ? 'text-red-500' : 'text-zinc-500 dark:text-zinc-400'}`} />
      </div>
      <div className="p-6 pt-0">
        <div className={`text-2xl font-bold ${alert ? 'text-red-600' : ''}`}>{value}</div>
        <p className="text-xs text-zinc-500 dark:text-zinc-400">{description}</p>
      </div>
    </div>
  );
}
